### ISSUE TITLE
Feedback from the Cookie Monsters

### ISSUE THREAD

**Issue by Jhdezj** [digitekh2i/Capstone-Online-shop#8]
1.- (suggestion) On line 724 from the css file (dial.btn) I would recommend to don't apply it to the button, and instead of using display: block, on line 239 from the css (search-hover:hover) 
use background-color: red, or the color you prefer

2.- Fix the search button link to the proper page.

3.- There are some problems with the arrows on the category page. It has to do with the relative position that you're using
and the media queries. Try to check for different screen sizes. 

4.- Try to hide the checkboxes by using  transform and translate with a negative value

**Comment by digitekh2i** [comment]
Thank you guys for your feedback.
